experiment:
  dataset: caltech101-7
  device: auto
  name: vae_mlp_Z40_L5_random
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: random_gaussian
  info_dim: 40
  redundancy_factor: 5
model:
  encoder_type: mlp
  inference_mode: amortized
training:
  alignment_beta: 0.1
  batch_size: 128
  epochs: 800
  log_interval: 50
  lr: 0.01
  use_gp_loss: false
views:
  centrist:
    input_dim: 254
    likelihood: gaussian
  gabor:
    input_dim: 48
    likelihood: gaussian
  gist:
    input_dim: 512
    likelihood: gaussian
  hog:
    input_dim: 1984
    likelihood: gaussian
  lbp:
    input_dim: 928
    likelihood: gaussian
  wm:
    input_dim: 40
    likelihood: gaussian
