experiment:
  dataset: caltech101-7
  device: auto
  name: caltech_v2_vae_mlp_Z10_L2_rep
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: repetition
  info_dim: 10
  redundancy_factor: 2
model:
  encoder_type: mlp
  inference_mode: amortized
training:
  batch_size: 128
  epochs: 800
  log_interval: 50
  lr: 0.01
views:
  centrist:
    input_dim: 254
    likelihood: gaussian
  gabor:
    input_dim: 48
    likelihood: gaussian
  gist:
    input_dim: 512
    likelihood: gaussian
  hog:
    input_dim: 1984
    likelihood: gaussian
  lbp:
    input_dim: 928
    likelihood: gaussian
  wm:
    input_dim: 40
    likelihood: gaussian
