experiment: {dataset: aloi, device: auto, seed: 42, name: aloi_rot_z64_cnn2d_semi_rand_L4}
kernels: {type: ng_sm, num_mixtures: 4, rff_samples: 1000}
training: {batch_size: 256, epochs: 500, lr: 0.001, use_amp: true, log_interval: 10,
  alignment_beta: 0.01, use_gp_loss: true, num_workers: 0}
views:
  view_left: {input_dim: 82944, likelihood: gaussian}
  view_center: {input_dim: 82944, likelihood: gaussian}
  view_right: {input_dim: 82944, likelihood: gaussian}
dataset_kwargs: {mode: rotation}
view_shapes:
  view_left: [3, 144, 192]
  view_center: [3, 144, 192]
  view_right: [3, 144, 192]
latent_space: {info_dim: 64, redundancy_factor: 4, ecc_type: random_gaussian}
model: {inference_mode: semi_amortized, encoder_type: cnn2d}
