experiment:
  dataset: 100leaves
  device: auto
  name: vae_mlp_Z64_L5_rep
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: repetition
  info_dim: 64
  redundancy_factor: 5
model:
  encoder_type: mlp
  inference_mode: amortized
training:
  alignment_beta: 0.1
  batch_size: 128
  epochs: 500
  log_interval: 50
  lr: 0.01
  use_gp_loss: false
views:
  margin:
    input_dim: 64
    likelihood: gaussian
  shape:
    input_dim: 64
    likelihood: gaussian
  texture:
    input_dim: 64
    likelihood: gaussian
