experiment:
  dataset: caltech
  device: auto
  name: caltech_z10_L2_rep
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: repetition
  info_dim: 10
  redundancy_factor: 2
model:
  encoder_type: mlp
  inference_mode: semi_amortized
training:
  alignment_beta: 0.01
  batch_size: 512
  epochs: 500
  log_interval: 10
  lr: 0.01
  use_amp: false
  use_gp_loss: true
views:
  wm:
    input_dim: 64
    likelihood: gaussian
  fac:
    input_dim: 448
    likelihood: gaussian
  fou:
    input_dim: 76
    likelihood: gaussian
  kar:
    input_dim: 64
    likelihood: gaussian
  pix:
    input_dim: 240
    likelihood: gaussian
  zer:
    input_dim: 47
    likelihood: gaussian
