experiment:
  dataset: 100leaves
  device: auto
  name: leaves_z64_cnn_L2_rand
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: random_gaussian
  info_dim: 64
  redundancy_factor: 2
model:
  encoder_type: cnn
  inference_mode: semi_amortized
training:
  alignment_beta: 0.01
  batch_size: 512
  epochs: 500
  log_interval: 10
  lr: 0.01
  use_amp: false
  use_gp_loss: true
views:
  shape:
    input_dim: 64
    likelihood: gaussian
  texture:
    input_dim: 64
    likelihood: gaussian
  margin:
    input_dim: 64
    likelihood: gaussian
