experiment:
  dataset: caltech101-7
  device: auto
  name: caltech_smlvm_Z5_L1
  seed: 42
kernels:
  num_mixtures: 4
  rff_samples: 1000
  type: ng_sm
latent_space:
  ecc_type: none
  info_dim: 5
  redundancy_factor: 1
model:
  encoder_type: mlp
  inference_mode: direct
training:
  batch_size: 128
  epochs: 800
  log_interval: 50
  lr: 0.01
views:
  centrist:
    input_dim: 100
    likelihood: gaussian
  gabor:
    input_dim: 48
    likelihood: gaussian
  gist:
    input_dim: 100
    likelihood: gaussian
  hog:
    input_dim: 100
    likelihood: gaussian
  lbp:
    input_dim: 100
    likelihood: gaussian
  wm:
    input_dim: 40
    likelihood: gaussian
